databases:
  - name: voterlist-db
    databaseName: voterlist_db
    user: voter_admin
    region: singapore
    plan: free

services:
  - type: web
    name: voterlist-nokorpheas
    env: python
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
      - key: TZ
        value: Asia/Phnom_Penh
      - key: DATABASE_URL
        fromDatabase:
          name: voterlist-db
          property: connectionString
      - key: SEED_DEMO_VOTERS
        value: "true"
